server {
    listen 80;

    # serve static/media files
    location /media/ {
    }

    # forward API requests to FastAPI app service
    location /{
        proxy_pass http://app:8080/;                                 # assumes app service is running on port 8080
        proxy_set_header Host $host;                                 # sends the domain the client used to the backend
        proxy_set_header X-Real-IP $remote_addr;                     # sends the IP address of the client to the backend
    }
}